@background = #111114
@foreground = #E5E5E5
@accentColor = #D62828
@buttonBackground = #1C1C1C
@componentBackground = #1A1A1F

Component.focusWidth = 1
Component.arc = 5
Button.arc = 5
ProgressBar.arc = 5
ScrollBar.showButtons = true

@selectionBackground = #A4161A
@selectionForeground = #FFFFFF
TabbedPane.selectedBackground = #8F1D2C

Slider.thumbColor = #FF0054
Slider.trackColor = #D62828
Slider.trackWidth = 4